language: node_js
node_js:
  - 8
  - 10
  - 12
  - 14
  - 16
  
branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+$/

before_install:
  - git config --local user.name "LTO Network"
  - git config --local user.email "info@ltonetwork.com"
install:
  - npm install
script:
  - npm test

stages:
  - name: test
    if: tag IS blank
jobs:
  include:
    - name: "Publish to NPM"
      stage: deploy
      if: tag IS present
      before_install:
        - sed -e "s/version = 0.0.0/version = $TRAVIS_TAG/" -i package.json
      before_script: skip
      script:
        - npx tsc
      deploy:
        provider: npm
        username: __token__
        password:
          secure: WlPldkWoyCpggKhL/j0tRahjFlOB4kpHu7RkSdz3ZweYYdHWqjfeS64C3KlCMmVPisEp62yOECCDksxEjRoTBJ8+SO8TV6a03T+qeu2x9nCW0MfB9OLmIzFsnr/ubWnzc6rknTaVpjdK3pSUnNloJrJcZymVTnjsHMHEk+xe3kLMnkM5FZNE7GOu7DsZcgyRY5hAb7nAluLx4FVpEir8bpCnlCPMKRHqiHpz8JybTWmT0DHetZLl6NGTriYatTcQM9GKZSydF23BC35Vph9CHusqMS+GbJYbEyfQ8FfkRNBqPYaXQac0ezdKeMVVGRqpL7aEmyefkfvo+8gLiamjCCXGL7tkcz9y/TbxEog8DLW2VVulZoxMYYZ9TXk/JB7J9s/iJrhH2H5kgqn1DWM2TL8AI3o7X+Z8m4rFhUBdAOeR18RlR7Ft5UpIxYmtRZfRHAPcvS4XoA9q8HQS1q2dWKeiRm13QoPcHKhyExZQ9PzOHNW4SF64FjVh3JFFIx/+rKVVewqOc3fi+lwK1zeiPWqnEA6GsoKPpCB7XuCRlHOvyOtmEB2Q1xOuNB9FFjkCUDw6ZZXUlxqxml8CWAw3/1D8fPVg4nbXaLMAeh2Y1dpnL4IT7vqPN0cC659v37DhdrW49zKucgfm4nI2uo7ByN0K1vv608p5bOMjLLgZ+uM=
        on:
          tags: true
        skip_cleanup: true


