language: node_js
node_js:
  - 8
  - 10
  - 12
  - 14
  - 16
  
branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+$/

before_install:
  - git config --local user.name "LTO Network"
  - git config --local user.email "info@ltonetwork.com"
install:
  - npm install
script:
  - npm test

stages:
  - name: test
    if: tag IS blank

jobs:
  include:
    - name: "Publish GitHub release"
      stage: deploy
      if: branch = main AND type = push
      install:
        - pip3 install bump2version
      before_script:
        - CURRENT_VERSION=$(git describe --tags --abbrev=0)
        - BUMP=3
        - if (git log $CURRENT_VERSION..HEAD | grep -q -i "\[bump:minor\]"); then BUMP=2; fi
        - if (git log $CURRENT_VERSION..HEAD | grep -q -i "\[bump:major\]"); then BUMP=1; fi
        - NEXT_VERSION=$(awk -F. -v OFS=. '{$'$BUMP'++;print}' <<< "$CURRENT_VERSION")
      script:
        - git tag "$NEXT_VERSION"
      before_deploy:
        - npm run build
      deploy:
        provider: releases
        api_key:
          secure: RalfF2YpboOqxCHNnywGGTkTN/Dkz9txg+cOXBFFW4flvKqjB6Wt0U6lbaCkCdPSeupjxq+MgqMepR9qp+EZNfIL49NXcN2WndpN94bLWeFR+Kiv5EPXo2otexSjsfBEfn7RuZgGQWm8a50oJ0wTk4AEiH00+5C4lyzcXXSvXHkl/egLGbpkhy2sV994nbuhYFyGafEVbDeOhqsqGDujO/qRRR/dPyLHT2rYFcEGqhP5B4y/bBpn3ujFeiqkDnDJ2jDm9ZFzMoumc8YqBQvJ+AjJopDWjyn1TjATMEmvq+E37XmbPC5EA3xvyRW043GFl1Iwaatrnhbf8G29kSUen2WcmdblczaZEX7d1ObOl9LT6X7jZEl7tgwb0cmd37aHqjjv70eyBghPbUSHknY8Gb4kNGQNz6IMTkCzTe4bI35r4kJG2Xc9SyDt9ITKhy7cbyW+shqYaSVvoVFWcZofVW6KwTqeaUYg6Ug2GHoOzJHtzEn6Rqk8FEgPYRwbjm9HBmCDqAEgJkqhMEqR7rsodmZ4Rfb7OKUTm4DqobQr6/+DS1kKgGyXQL5hkQOhyJ8rhieqpuOotn57lvzoy8ley2ZfddBhD/Mz6VHbb4YfwnDzOqfFxpIJw2TkfM38oigta9ysXn2T+F0bqnftNsMPl2/stZ0EX+NCdn9fxibYlBk=
        skip_cleanup: true
        on:
          all_branches: true
    - name: "Publish to NPM"
      stage: deploy
      if: tag IS present
      before_install:
        - npm version "$TRAVIS_TAG"
      before_script: skip
      script:
        - npx tsc
        deploy:
        provider: npm
        email: andrea@ltonetwork.com
        api_key:
          secure: LGZloKiN82cT0cruME0WA7NiTucHaeSSlv5FFySKw1MNSDUrUoo6riybQVSKDKcYbzTU2HlV2MqGVB2hsqhvaSw7Z8rOzchoD6bkXSSrteayBw5jvdDmGItIgGVh2smPZz8hXktDvS6jLFno1gqyHv5sqjXBzy4zGj9rRpSpoPoipowyOfv42DLRDOqiDAA/qau1zYwcyey9tMZ5CZyV14teby6dKy8vsGo814nJkylfaBIxzPgLMOjjAA9dPHt9+TtbLL92KTDq645Qi1jCXIJN0oABwWKqI/qVbZ9Llb8rXqu0/yiL4USv4SCQnzfALTzz9WxvKVaCVHLiY5+iDjWsFrff23yJwWwhP8oFAQ+P0wHMS9l4JjL5k198Ud5EEJYxrF4qLwQ2y0Em4OpaZvy44zRdPWv65bgGbj4jLCoiFVs2Zal/+BpiJB1L5Xb3EDEGOZIrN/N4tYxTbeQwVUk8b37aMkpB1D8fXZWD+p9ayXhKdu6GEJpFjEQ/LXCdpMozETupAaOVsafWR4AShHEAuxb3zTYKdlLsfkZ1ToMelL5KkExWYk0ON22D4TWqSyz8NngVmKx1DYtbaVDbloCYyMKIqes2tqkrcwe3r1ULjRtHLHY0nxiIZy3MczaFHWXUCMhnR9wUUCIuZilU+4mlmtZINhzI+n78OZ0Ab94=
        on:
          tags: true
        skip_cleanup: true
